version: "3.8"

services:
  nginx:
    build: ./requirements/nginx/  # путь к Dockerfile для сборки образа
    container_name: nginx # имя контейнера (удобно при отладке)
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html  # подключаем том с файлами WordPress
      - ./secrets:/etc/nginx/ssl
    depends_on:
      - wordpress
    restart: unless-stopped
    #использовать ли докер сикретс для шифрования или достаточно того, что я создала папку сикретс и положила ее в гитигнор?
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    # healthcheck помогает понять готов ли php-fpm
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm82"]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql  # сохраняем данные базы вне контейнера
    restart: unless-stopped
    env_file:
      - .env

volumes:
  mariadb_data:
  wp_data: