version: "3.8"

services:
  nginx:
    build: ./requirements/nginx/  # путь к Dockerfile для сборки образа
    container_name: nginx # имя контейнера (удобно при отладке)
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html  # мб тут не просто веб, а requirements/wordpress/web:, перепроверь
      - ./secrets:/etc/nginx/ssl
    depends_on:
      - wordpress
    restart: unless-stopped
    #использовать ли докер сикретс для шифрования или достаточно того, что я создала папку сикретс и положила ее в гитигнор?

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - ./web:/var/www/html  # монтируем локальную папку web в контейнер
    # healthcheck помогает понять готов ли php-fpm
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm82"]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql  # сохраняем данные базы вне контейнера
    restart: unless-stopped
    #environment:
     # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
     # MYSQL_DATABASE: wordpress
     # MYSQL_USER: wp_user
     # MYSQL_PASSWORD_FILE: /run/secrets/db_password

volumes:
  mariadb_data:
    driver: local